---
development:
  cloud_name: drriuukay
  api_key: '999522593171591'
  api_secret: 6Sii_NiXoechh2l9yBVowkNbBOk
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: drriuukay
  api_key: '999522593171591'
  api_secret: 6Sii_NiXoechh2l9yBVowkNbBOk
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: drriuukay
  api_key: '999522593171591'
  api_secret: 6Sii_NiXoechh2l9yBVowkNbBOk
  enhance_image_tag: true
  static_file_support: false
